pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
     parameters {
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'Select Action')
                }
    stages {
        stage('Init'){
            steps{
                sh 'cd 00-vpc'
                sh 'terraform init --reconfigure'
            }
        }
        stage('Plan'){
            steps{
                withAWS(region: 'us-east-1', credentials:'aws-creds'){
                    sh 'cd 00-vpc'
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Deploy'){
            when {
                expression { env.GIT_BRANCH != "origin/main"}
            }
            steps{
                sh 'echo This is Deploy'
            }
        }
        stage('Print Params'){
            steps{
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"  
            }
        }
    }
    post {
     always{
        echo "This section runs always"
        deleteDir() 
     }
     success{
        echo "This section runs when pipleline success"
     }
     failure{
        echo "This section runs when pipleline failure"
     }
    }
}

